<%@ page contentType="text/html;charset=UTF-8" %><%@ page import="com.shopsphere.model.Product,java.util.List,java.util.Map,com.shopsphere.model.User" %>
<!doctype html><html lang="en"><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>${product.name} — ShopSphere</title><link rel="stylesheet" href="${pageContext.request.contextPath}/assets/css/app.css"></head><body>
<div class="announcement-bar"><span>SHOPSPHERE COLLECTION</span></div><header class="nav-header"><div class="container nav-inner"><nav class="nav-menu"><a class="nav-link" href="${pageContext.request.contextPath}/">Shop</a><a class="nav-link" href="${pageContext.request.contextPath}/products">Collections</a></nav><a class="brand-logo" href="${pageContext.request.contextPath}/">ShopSphere</a><div><a class="btn ghost" href="${pageContext.request.contextPath}/wishlist">Wishlist</a><a class="btn ghost" href="${pageContext.request.contextPath}/cart">Cart</a></div></div></header>
<%
Product pdObj = (Product) request.getAttribute("product");
String pdImg = "https://images.unsplash.com/photo-1526170375885-4d8ecf77b99f?auto=format&fit=crop&w=1200&q=85";
if (pdObj != null && pdObj.getImageUrl() != null && !pdObj.getImageUrl().trim().isEmpty()) {
    pdImg = pdObj.getImageUrl();
} else if (pdObj != null && pdObj.getCategoryId() == 2) {
    pdImg = "https://images.unsplash.com/photo-1495446815901-a7297e633e8d?auto=format&fit=crop&w=1200&q=85";
} else if (pdObj != null && pdObj.getCategoryId() == 3) {
    pdImg = "https://images.unsplash.com/photo-1483985988355-763728e1935b?auto=format&fit=crop&w=1200&q=85";
}
%>
<main class="container section"><a href="${pageContext.request.contextPath}/products" class="eyebrow">← BACK TO SHOP</a><div class="detail-grid" style="margin-top:22px"><div class="product-image detail-image"><img src="<%= pdImg %>" alt="${product.name}"><span class="product-tag">${product.stock > 0 ? 'IN STOCK' : 'OUT OF STOCK'}</span></div><div><span class="chip">${product.brand}</span><h1>${product.name}</h1><p class="muted">${product.description}</p><div class="price">₹${product.price}</div><p><span class="chip">${product.stock} in stock</span></p><%if(((Product)request.getAttribute("product")).getStock()>0){%><form method="post" action="${pageContext.request.contextPath}/cart" class="inline"><input type="hidden" name="productId" value="${product.productId}"><input type="number" name="quantity" value="1" min="1" max="${product.stock}" style="width:90px"><button>Add to bag</button></form><%}%></div></div>
<div class="section-head" style="margin-top:75px"><div><span class="eyebrow">REVIEWS</span><h2>Customer feedback</h2></div></div>
<div class="grid review-grid"><%List<Map<String,Object>> reviews=(List<Map<String,Object>>)request.getAttribute("reviews");if(reviews==null||reviews.isEmpty()){%><div class="card empty"><h3>No reviews yet</h3><p class="muted">Be the first customer to review this product.</p></div><%}else{for(Map<String,Object> r:reviews){%><article class="card"><strong><%=r.get("name")%></strong><div class="rating">★ <%=r.get("rating")%>/5</div><p style="margin:8px 0"><%=r.get("reviewText")==null?"":r.get("reviewText")%></p><small class="muted"><%=r.get("createdAt")%></small></article><%}}%></div>
<%User u=(User)session.getAttribute("loggedInUser");if(u!=null){%><div class="card" style="margin-top:18px"><span class="eyebrow">YOUR REVIEW</span><h3 style="font-size:36px;margin:8px 0 18px">Share your experience.</h3><form method="post" action="${pageContext.request.contextPath}/reviews"><input type="hidden" name="productId" value="${product.productId}"><div class="field"><label>Rating</label><select name="rating" required><option value="5">5 — Excellent</option><option value="4">4 — Great</option><option value="3">3 — Good</option><option value="2">2 — Fair</option><option value="1">1 — Poor</option></select></div><div class="field"><label>Your review</label><textarea name="reviewText" rows="4" maxlength="1000"></textarea></div><button type="submit">Publish review</button></form></div><%}%>
</main><footer class="main-footer"><div class="container"><div class="footer-bottom"><span>© 2026 ShopSphere</span><a href="${pageContext.request.contextPath}/products">Continue shopping</a></div></div></footer></body></html>